### ISSUE TITLE
Regex breaks on windows machine due to backslash.

### ISSUE THREAD

**Issue by NicoBeyer** [simonlast/node-persist#62] opened 2016-09-01 17:53 UTC
Suggestion: String replace 53 with: btoaPathSepRegExp = new RegExp(path.sep.replace('\\','\\\\'), 'g')

`SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at Object.<anonymous> (C:\Users\lukee_000\WebstormProjects\services\ShopifyService\node_modules\node-persist\src\local-storage.js:53:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\lukee_000\WebstormProjects\services\ShopifyService\node_modules\node-persist\src\node-persist.js:6:20)
    at Module._compile (module.js:413:34)`

**Comment by HugoGiraudel** [comment] 2016-09-01 20:40
Reproduced on Windows 10.

**Comment by HugoGiraudel** [comment] 2016-09-01 20:57
Fix proposed by @NicoBeyer did not work (syntax error because the closing quote of the first parameter is escaped by the backslash). A possible fix found by @egiraudel is:

```js
btoaPathSepRegExp = new RegExp(path.sep.replace('\\','\\\\'), 'g')
```

**Closed** 2016-09-01 21:09 UTC

**Comment by akhoury** [comment] 2016-09-01 21:10
`node-persist@1.0.1 published`, thank you both

**Comment by akhoury** [comment] 2016-09-02 03:19
fyi- `node-persist@2.0.0` is published, using md5 hash for filenames now
The reason it's a major release at `2.0.0`, is because it wont be able to read your previous data.
https://github.com/simonlast/node-persist#200-change-logs
https://github.com/simonlast/node-persist/commit/0eaf17a307fb0fa7e6e74a00ab71fc6fc71efa37
